server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
            - Method=GET,POST,PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
            - Method=GET,POST,PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/cart/(?<segment>.*), /$\{segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
            - Method=GET,POST,PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product/(?<segment>.*), /$\{segment}

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order/(?<segment>.*), /$\{segment}